name: Benchmark
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache SBT dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ hashFiles('**/build.sbt') }}
      - name: Build and run JMH benchmark
        run: |
          sbt clean compile 
          sbt 'benchmarks/runBenchmarks'
      - name: JMH Benchmark Action
        uses: kitlangton/jmh-benchmark-action@v0.1.1
        with:
          jmh-output-path: benchmarks/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
