name: Benchmark
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache SBT dependencies
        uses: coursier/cache-action@v6
      - name: Build and run JMH benchmark
        run: |
          sbt clean compile 
          sbt 'benchmarks/jmh:run -i 3 -wi 3 -f1 -t1 -rf json -rff output.json .*'
      - name: JMH Benchmark Action
        uses: kitlangton/jmh-benchmark-action@main
        with:
          jmh-output-path: benchmarks/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
